name: "Build with cached packs"
inputs:
  gh-token:
    description: "GitHub Token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install jq (JSON processor) if not found
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y jq
        else
          echo "jq is already installed. Skipping install..."
        fi
      shell: bash

    - name: Download Packs Data
      run: |
        # Find the latest packs upload workflow.
        run_id=$(gh run list --workflow="post_release.yaml" --limit 1 --status=success --json databaseId | jq -r '.[0].databaseId')
        # Remove any downloaded artifacts, should they exist.
        rm -rf ./downloaded_artifacts
        # Download the latest artifact to a new dir.
        gh run download ${run_id} --name build-packs --dir ./downloaded_artifacts
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}

    - name: Unpack packs data
      run: |
        # Ensure the correct folders exist.
        mkdir -p .docusaurus/packs-integrations
        # Move the files to their correct places in the checked out repository
        mv downloaded_artifacts/.docusaurus/packs-integrations/* .docusaurus/packs-integrations
        mkdir -p static/img/packs
        mv downloaded_artifacts/build/packs/* static/img/packs
        # Clean up. 
        rm -rf downloaded_artifacts
      shell: bash

    - name: Build
      run: |
        rm -rf build
        npm run build
        exit_code=$?
        echo "BUILD_EXIT_CODE=$$exit_code" >> $GITHUB_ENV
      shell: bash
