branches: [master]
repositoryUrl: https://github.com/spectrocloud/librarium
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - analyzeCommitsCmd: echo 'NEW_VERSION=false' > VERSION.env
      verifyReleaseCmd: |-
        echo 'export VERSION=${nextRelease.version}
        NEW_VERSION=true' > VERSION.env
  - - "@semantic-release/github"
    - assets:
        - "*.zip"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
  - - "@semantic-release/npm"
    - npmPublish: false
