// Sidebar for the PaletteAI Inference Launchpad docs collection.
//
// This is a separate file from sidebars.js on purpose. `docs:version:<id>`
// snapshots the entire sidebar module into the frozen copy, so sharing
// sidebars.js would freeze Palette's whole sidebar definition into every
// Launchpad version. Each independently versioned product needs its own file.
//
// `dirName: "."` is relative to this collection's own content root, not to
// docs/docs-content. Do not rename the `launchpadSidebar` key after the first
// version is cut -- the key is baked into every frozen sidebar snapshot.

// @ts-check

const { createPrivacyLink } = require("./sidebarPrivacyLink");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  launchpadSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "html",
      value: createPrivacyLink(false, "privacy-settings"),
    },
  ],
};

module.exports = sidebars;
