/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const { createPrivacyLink } = require("./sidebarPrivacyLink");

const privacyLinkDocs = createPrivacyLink();
const privacyLinkTutorial = createPrivacyLink(false, "privacy-settings");
const privacyLinkDownloads = createPrivacyLink(false, "privacy-settings");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "html",
      value: privacyLinkDocs,
    },
  ],
  tutorialSidebar: [
    { type: "autogenerated", dirName: "tutorials" },
    {
      type: "html",
      value: privacyLinkTutorial,
    },
  ],
  downloadsSidebar: [
    { type: "autogenerated", dirName: "downloads" },
    {
      type: "html",
      value: privacyLinkDownloads,
    },
  ],
};

module.exports = sidebars;
