#!/usr/bin/env bash

prompt() {
  local var_name=$1
  local default_value=$2

  read -p "$var_name [$default_value]: " input
  echo "${input:-$default_value}"
}

# Prompt for values (defaults = last release)
RELEASE_NAME=$(prompt "RELEASE_NAME" "4-8-c")
RELEASE_VERSION=$(prompt "RELEASE_VERSION" "4.8.c")
RELEASE_SPECTRO_CLI_VERSION=$(prompt "RELEASE_SPECTRO_CLI_VERSION" "4.8.4")
RELEASE_REGISTRY_VERSION=$(prompt "RELEASE_REGISTRY_VERSION" "4.8.4")
RELEASE_DATE=$(prompt "RELEASE_DATE" "April 5, 2026")
RELEASE_CANVOS=$(prompt "RELEASE_CANVOS" "4.8.18")
RELEASE_TERRAFORM_VERSION=$(prompt "RELEASE_TERRAFORM_VERSION" "0.28.3")
RELEASE_PALETTE_CLI_VERSION=$(prompt "RELEASE_PALETTE_CLI_VERSION" "4.8.10")
RELEASE_PALETTE_CLI_SHA=$(prompt "RELEASE_PALETTE_CLI_SHA" "06e3d139fcfec018830ab2a9e03ee0c760dfc8cd8b0283eca93a43c86ae68b24")
RELEASE_EDGE_CLI_VERSION=$(prompt "RELEASE_EDGE_CLI_VERSION" "4.8.18")
RELEASE_EDGE_CLI_SHA=$(prompt "RELEASE_EDGE_CLI_SHA" "54f69d28e9cfd0f651c451ae2d008366cdb9da4be90ce2bcaccb743b488b3c73")
RELEASE_VMWARE_KUBERNETES_VERSION=$(prompt "RELEASE_VMWARE_KUBERNETES_VERSION" "1.32.9")
RELEASE_VMWARE_OVA_URL=$(prompt "RELEASE_VMWARE_OVA_URL" "https://vmwaregoldenimage-console.s3.amazonaws.com/u-2204-0-k-1329-0.ova")
RELEASE_VMWARE_FIPS_OVA_URL=$(prompt "RELEASE_VMWARE_FIPS_OVA_URL" "https://vmwaregoldenimage-console.s3.amazonaws.com/u-2004-0-k-1329-fips.ova")
RELEASE_PCG_KUBERNETES_VERSION=$(prompt "RELEASE_PCG_KUBERNETES_VERSION" "1.32.9")
RELEASE_HIGHEST_KUBERNETES_VERSION=$(prompt "RELEASE_HIGHEST_KUBERNETES_VERSION" "1.35.5")

echo ""
echo "Exporting variables..."

cat > release.env <<EOF
export RELEASE_NAME=$RELEASE_NAME
export RELEASE_VERSION=$RELEASE_VERSION
export RELEASE_SPECTRO_CLI_VERSION=$RELEASE_SPECTRO_CLI_VERSION
export RELEASE_REGISTRY_VERSION=$RELEASE_REGISTRY_VERSION
export RELEASE_DATE="$RELEASE_DATE"
export RELEASE_CANVOS=$RELEASE_CANVOS
export RELEASE_TERRAFORM_VERSION=$RELEASE_TERRAFORM_VERSION
export RELEASE_PALETTE_CLI_VERSION=$RELEASE_PALETTE_CLI_VERSION
export RELEASE_PALETTE_CLI_SHA=$RELEASE_PALETTE_CLI_SHA
export RELEASE_EDGE_CLI_VERSION=$RELEASE_EDGE_CLI_VERSION
export RELEASE_EDGE_CLI_SHA=$RELEASE_EDGE_CLI_SHA
export RELEASE_VMWARE_KUBERNETES_VERSION=$RELEASE_VMWARE_KUBERNETES_VERSION
export RELEASE_VMWARE_OVA_URL="$RELEASE_VMWARE_OVA_URL"
export RELEASE_VMWARE_FIPS_OVA_URL="$RELEASE_VMWARE_FIPS_OVA_URL"
export RELEASE_PCG_KUBERNETES_VERSION=$RELEASE_PCG_KUBERNETES_VERSION
export RELEASE_HIGHEST_KUBERNETES_VERSION=$RELEASE_HIGHEST_KUBERNETES_VERSION
EOF

echo "Saved to release.env"
echo "Done."
