apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-docs
  namespace: {{ .Chart.Name }}
spec:
  concurrencyPolicy: Forbid
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600 
      template:
        spec:
          serviceAccountName: restart-docs
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/{{ .Chart.Name }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-docs
  namespace: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-docs
subjects:
  - kind: ServiceAccount
    name: restart-docs
    namespace: {{ .Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-docs
  namespace: {{ .Chart.Name }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["{{ .Chart.Name }}"]
    verbs: ["get", "patch"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: restart-docs
  namespace: {{ .Chart.Name }}