apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels: 
    group: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: restart-docs
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80