apiVersion: v1
kind: Service
metadata:
  labels:
    prow.k8s.io/job: librarium_build
  name: librarium-service
  namespace: test-pods
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    prow.k8s.io/job: librarium_build
    app: spectro
    module: librarium
  type: LoadBalancer
