# This workflow will run Eslint and Test cases on the codebase
# Jest is the default test runner for the project/

name: Eslint and Test cases

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "src/**"
      - "plugins/**"
      - "utils/**"
      - "package.json"
      - "package-lock.json"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "24"
jobs:
  run-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - run: exit 0

  build:
    name: Build
    needs: [run-ci]
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - run: npm ci

      - name: Eslint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test
