
name: "Generate Patch Release Notes"

on:
  workflow_dispatch:
    inputs:
      jira_ticket:
        description: "The Jira ticket for the patch release (e.g., DOC-2815)"
        required: true
    base_branch:
      description: "The base branch for the patch release PR (default: master)"
      required: true
  push:
    branches:
      - doc-2813-generate-patch-rl-notes

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  SUPER_API_TOKEN: ${{ secrets.SUPER_API_TOKEN }}
  NODE_VERSION: "24"
  JIRA_TICKET: ${{ github.event_name == 'push' && 'DOC-2815' || github.event.inputs.jira_ticket }}
  BASE_BRANCH: ${{ github.event_name == 'push' && 'doc-2813-generate-patch-rl-notes' || github.event.inputs.base_branch }}
  ALGOLIA_APP_ID: "123456789"
  ALGOLIA_INDEX_NAME: "123456789"
  ALGOLIA_SEARCH_KEY: "123456789"

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Retrieve Credentials
        id: import-secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: https://vault.prism.spectrocloud.com
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: /providers/github/organizations/spectrocloud/token?org_name=spectrocloud token | VAULT_GITHUB_TOKEN

      - name: Checkout Librarium Repository
        uses: actions/checkout@v6
        with: 
          repository: spectrocloud/librarium
          ref: ${{ env.BASE_BRANCH }}
          token: ${{ steps.import-secrets.outputs.VAULT_GITHUB_TOKEN }}
  
      - name: Set Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm" 

      - run: |
          npm ci
      
      - name: Execute Script to Generate Patch Release Notes
        run: |
          PATCH_RELEASE_TICKET=${{ env.JIRA_TICKET }} make generate-patch-release-notes

      - name: Create a PR with generated patch release notes
        env:
          GH_TOKEN: ${{ steps.import-secrets.outputs.VAULT_GITHUB_TOKEN }}
        run: |
          # Create a new branch
          branch_name="${{ env.JIRA_TICKET }}-generate-patch-notes-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$branch_name"

          # Commit and push the changes
          git add docs/docs-content/release-notes/release-notes.md
          git commit -m "docs: add patch release notes for ${{ env.JIRA_TICKET }}"
          git push origin $branch_name

          # Create the pull request
          pr_body='
          ## Describe the Change
          This PR adds the patch release notes for the Jira ticket `${{ env.JIRA_TICKET }}` to the `release-notes.md` file.'
          output=$(gh pr create --base "${{ env.BASE_BRANCH }}" --title "docs: add patch release notes for ${{ env.JIRA_TICKET }}" --body "$pr_body")
          pr_url=$(echo "$output" | grep -o "https://[^ ]*")
          echo "PR successfully created $pr_url."

          # Save the PR URL as an environment variable
          echo "GITHUB_PATCH_RELEASE_NOTES_PR=$pr_url" >> $GITHUB_ENV

      - name: Success Slack Notification
        if: ${{ env.GITHUB_PATCH_RELEASE_NOTES_PR  != ''}}
        uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIVATE_TEAM_TEST_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACKIFY_MARKDOWN: true
          ENABLE_ESCAPES: true
          SLACK_MESSAGE: 'A new PR with updated patch release notes was created for Jira ticket `${{ env.JIRA_TICKET }}`. Please review ${{env.GITHUB_PATCH_RELEASE_NOTES_PR}} for more details.'

      - name: Failure Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIVATE_TEAM_TEST_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACKIFY_MARKDOWN: true
          ENABLE_ESCAPES: true
          SLACK_MESSAGE: 'The generate patch release notes job for Jira ticket `${{ env.JIRA_TICKET }}` in `${{ github.repository }}` failed. [View details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
          
