# This workflow builds a Docker image and pushes it to the GitHub Container Registry (GHCR) every weekday at 22:15 UTC.
# This image is used to facilitate an offline Documentation expericence. Customers and stakeholders can use this image to view the documentation without an active internet connection.
# The image is signed using the sigstore/cosign-installer action to ensure the integrity of the image.
# Visit https://docs.spectrocloud.com/vertex/install-palette-vertex/airgap/offline-docs/ to learn more about the offline Documentation experience.
# This workflow supports on-demand execution using the workflow_dispatch event.

name: Nighly Docker Build

on:
  schedule:
    - cron: '15 22 * * 1-5'  # 22:15 UTC, Monday through Friday
  workflow_dispatch:


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # We cannot use our production values for nightly Docker builds as that would leak our production secrets.
  ALGOLIA_ADMIN_KEY: "123456789"
  ALGOLIA_APP_ID: "123456789"
  ALGOLIA_SEARCH_KEY: "123456789"
  ALGOLIA_INDEX_NAME: "madeup-index"
  PALETTE_API_KEY: ${{ secrets.PALETTE_API_KEY }}
  DISABLE_PACKS_INTEGRATIONS: ${{ secrets.DISABLE_PACKS_INTEGRATIONS }}
  DISABLE_SECURITY_INTEGRATIONS: ${{ secrets.DISABLE_SECURITY_INTEGRATIONS }}
  SHOW_LAST_UPDATE_TIME: ${{ secrets.SHOW_LAST_UPDATE_TIME }}
  DSO_AUTH_TOKEN: ${{ secrets.DSO_AUTH_TOKEN }}
  SEERS_CMP_KEY: ${{ secrets.SEERS_CMP_KEY }}
  NODE_VERSION: "24"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager-cache: false

      - run: npm ci

      - name: Build
        run: |
          touch .env
          make build-ci
      
      - name: Build with cached packs
        id: cached_packs
        if: ${{ env.BUILD_EXIT_CODE == '5' }}
        uses: ./.github/actions/build-cached-packs
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build with cached CVEs
        id: cached_cves
        if: ${{ env.BUILD_EXIT_CODE == '7' }}
        uses: ./.github/actions/build-cached-cves
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ghcr.io/${{ github.repository }}:nightly

      - name: Login to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        id: build-and-push
        with:
          context: .
          file: ./Dockerfile-offline
          # build-args: 
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:nightly
          labels: ${{ steps.meta.outputs.labels }}

      - uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

      - name: Image Signing
        run: |
          cosign sign --yes \
          -a "repo=${REPOSITORY}" \
          -a "workflow=${WORKFLOW_NAME}" \
          -a "ref=${REF_SHA}" \
          -a "owner=Spectro Cloud" \
          --key env://COSIGN_PRIVATE_KEY --recursive "${TAGS}@${DIGEST}"
        env:
          REPOSITORY: ${{ github.repository }}
          WORKFLOW_NAME: ${{ github.workflow }}
          REF_SHA: ${{ github.sha }}
          TAGS: ghcr.io/${{ github.repository }}:nightly
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

  container-prune:
    name: "Container Image Cleanup"
    needs: [build]
    if: ${{ needs.build.result == 'success' }}
    uses: ./.github/workflows/container-prune.yaml
    secrets: inherit
