name: Post Release Processing
# This workflow is triggered when a workflow run of the "Release to Production" workflow is completed or when manually triggered.
# The primary purpose of this workflow is to build the site, copy the packs data and upload it as artifacts.
# The packs data can be used as a fallback when the Palette API cannot return a packs list.

on:
  workflow_run:
    workflows: ["Release to Production"]
    types: [completed]
  workflow_dispatch:
  push: # Remove after testing
    branches:
      - caching-packs-doc-1460

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FULLSTORY_ORGID: ${{ secrets.FULLSTORY_ORGID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
  ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
  PALETTE_API_KEY: ${{ secrets.PALETTE_API_KEY }}
  DISABLE_PACKS_INTEGRATIONS: ${{ secrets.DISABLE_PACKS_INTEGRATIONS }}

jobs:

  create-assets:
    name: asset-builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Website
        run: make build

      - name: Upload Build Packs
        uses: actions/upload-artifact@v4
        with:
          name: "build-packs"
          path: |
            build/packs
            .docusaurus/packs-integrations
            .docusaurus/plugin-packs-integrations
          if-no-files-found: error
          retention-days: 7
