name: Testing Versios

on:
  push:
    branches: ['ci-**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  APPZI_TOKEN: ${{ secrets.APPZI_TOKEN }}
  MENDABLE_API_KEY: ${{ secrets.MENDABLE_API_KEY }}
  FULLSTORY_ORGID: ${{ secrets.FULLSTORY_ORGID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}


concurrency:
  group: production-${{ github.workflow }}
  cancel-in-progress: true  

jobs:
  build:
    name: Build Website
    runs-on: ["self-hosted", "linux", "x64", "vcenter3"]
    # runs-on: 
    #   group: 'Doc Runners'
    #   labels: docbot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "master"


      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Compile
        run: |
          make versions-ci
          make build
