name: Testing Versios

on:
  push:
    branches: ['ci-**']
  workflow_dispatch:
    inputs:
      useGitHubHostedLargeRunner:
        description: 'Use the GitHub-hosted large runner'
        required: false
        default: false
    

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  APPZI_TOKEN: ${{ secrets.APPZI_TOKEN }}
  MENDABLE_API_KEY: ${{ secrets.MENDABLE_API_KEY }}
  FULLSTORY_ORGID: ${{ secrets.FULLSTORY_ORGID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}


concurrency:
  group: production-${{ github.workflow }}
  cancel-in-progress: true  

jobs:
  build-large-runner:
    name: Build Website
    if : ${{ github.event.inputs.useGitHubHostedLargeRunner == 'true' }}
    # runs-on: ${{ (inputs.useGitHubHostedLarge) && fromJSON('') || '["self-hosted", "linux", "x64", "vcenter3"]' }}
    # runs-on: ["self-hosted", "linux", "x64", "vcenter3"]
    # runs-on: ["self-hosted", "linux", "x64", "vcenter3"]
    #   group: ''
    #   labels: ''
    runs-on: 
      group: 'Doc Runners'
      labels: docbot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Compile
        run: |
          make build

  build-self-hosted-runner:
    name: Build Website
    if : ${{ github.event.inputs.useGitHubHostedLargeRunner == 'false' }}
    runs-on: ["self-hosted", "linux", "x64", "vcenter3"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Compile
        run: |
          make build