name: Test & Validate


on:
  push:
    branches-ignore: [ main ]
env:
  GITHUB_TOKEN: ${{ github.token }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  GATSBY_APPZI_TOKEN: ${{ secrets.GATSBY_APPZI_TOKEN }}
  GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
  GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - name: Build
        run: |
          make build

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          retention-days: 1

  update-site:
    name: Update Site
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download my-folder
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Upload to AWS
        run: |
          ls -la public/
          aws s3 sync --cache-control 'max-age=604800' --exclude '*.html' --exclude '*page-data/*' --exclude '*.txt' --exclude '*.xml' --exclude '*/sw.js' public/ s3://docs-latest.spectrocloud.com --delete
          aws s3 sync --cache-control 'max-age=0, s-maxage=604800' public/ s3://docs-latest.spectrocloud.com --delete
          aws cloudfront create-invalidation --distribution-id EV0DH5A7CFZBY --paths "/*"
                  