name: Test & Validate


on:
  push:
    branches-ignore: [ main ]
env:
  GITHUB_TOKEN: ${{ github.token }}
  LINT_VERSION: "1.25.1"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - name: Build
        run: |
          make build