name: Test & Validate


on:
  push:
    branches-ignore: [ main ]
env:
  GITHUB_TOKEN: ${{ github.token }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - name: Build
        run: |
          make build

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          retention-days: 1

  update-site:
    name: Update Site
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download my-folder
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Upload to AWS
        run: |
          ls -la public/
          