name: Versioned URL check

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:

concurrency:
  group: versioned-url-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "24"

jobs:
  versioned-link-check:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Generate versioned links report
        run: bash scripts/generate-versioned-links-report.sh

      - name: Check versioned relative links
        run: bash scripts/versioned-url-checker.sh
        env:
          REPORT_FILE: ${{ github.workspace }}/versioned_links_report.json
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PRIVATE_TEAM_WEBHOOK }}

      - name: Failure Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIVATE_TEAM_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACKIFY_MARKDOWN: true
          ENABLE_ESCAPES: true
          SLACK_MESSAGE: 'The versioned-url-check job in `${{ github.repository }}` failed. [View details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).'